apiVersion: v1
kind: Secret
metadata:
  name: bookmyshow-secrets
  namespace: bookmyshow
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb+srv://kumawatd185_db_user:dXwd4WO8fK8Cyu2f@cluster0.kmoxgdq.mongodb.net/bookmyshow?appName=Cluster0"
  MAIL_USERNAME: "kumawatk2020@gmail.com"
  MAIL_PASSWORD: "your-gmail-app-password"
  OPENAI_API_KEY: "your-openai-key"
  TMDB_API_KEY: "your-tmdb-key"
